### ISSUE TITLE
1.18.2 support?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [heyunahere/missiles#3]

**Comment by heyunahere** [comment]
I can do that.

Most of the features would still work in previous versions except for the radar.

**Comment by vadim-a-yegorov** [comment]
> I can do that.

Awesome! Try just change pack_format to 8 and remove radar, what files are related to radar?

**Comment by heyunahere** [comment]
Already done, while I didn't test all the variants yet I added support for versions 1.13 to latest 1.20.1.

Thank you for the suggestion!
